# databases:
#   - name: comongdb
#     plan: free
#     databaseName: comong
#     user: comong

# services:
#   - type: web
#     plan: free
#     name: comong
#     runtime: python
#     buildCommand: "./build.sh"
#     startCommand: "gunicorn comong_project.wsgi" #python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: comongdb
#           property: connectionString
#       - key: SECRET_KEY
#         generateValue: true
#       - key: WEB_CONCURRENCY
#         value: 4

services:
  - type: web
    name: my-django-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
