# Generated by Django 3.2.25 on 2024-08-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_make_url_field_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
