# Generated by Django 3.2.25 on 2024-08-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_alter_notice_content_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(choices=[(0, '전공 과목'), (1, '프로젝트'), (2, '대학원'), (3, '학부 연구생'), (4, '인턴'), (5, '구인'), (6, '백엔드'), (7, '프론트')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='join_post',
            name='tag',
        ),
        migrations.AddField(
            model_name='join_post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='Community.HashTag'),
        ),
        migrations.RemoveField(
            model_name='sub_post',
            name='tag',
        ),
        migrations.AddField(
            model_name='sub_post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='Community.HashTag'),
        ),
    ]
