# Generated by Django 3.2.25 on 2024-08-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_auto_20240813_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_board', models.URLField(max_length=100, null=True)),
            ],
        ),
    ]
