# Generated by Django 2.2 on 2024-07-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0005_Make_HashTag_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='profs',
            field=models.CharField(max_length=15),
        ),
    ]
