# Generated by Django 3.2.25 on 2024-08-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0005_scrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='scrap_board',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
