# Generated by Django 2.2 on 2024-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0006_auto_20240728_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='profs',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='board',
            name='sub',
            field=models.CharField(max_length=30),
        ),
    ]
