# Generated by Django 3.2.25 on 2024-08-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0006_alter_scrap_scrap_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='scrap_board',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
