# Generated by Django 3.2.25 on 2024-07-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0008_auto_20240729_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board_pk',
            field=models.IntegerField(null=True),
        ),
    ]
