# Generated by Django 3.2.25 on 2024-08-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0009_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='likes',
            name='sub_post',
        ),
        migrations.AddField(
            model_name='likes',
            name='sub_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.sub_post'),
        ),
    ]
