# Generated by Django 3.2.25 on 2024-08-14 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0011_alter_likes_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join_comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('join_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.join_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
