# Generated by Django 3.2.25 on 2024-08-15 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_blogpost_comment'),
        ('Community', '0012_join_comment'),
    ]

    operations = [
    ]
