# Generated by Django 3.2.25 on 2024-08-14 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0012_join_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
            preserve_default=False,
        ),
    ]
