# Generated by Django 3.2.25 on 2024-08-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0013_auto_20240814_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_comment',
            name='resume_id',
            field=models.TextField(null=True),
        ),
    ]
