# Generated by Django 3.2.25 on 2024-08-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0014_join_comment_resume_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_comment',
            name='resume_id',
            field=models.IntegerField(null=True),
        ),
    ]
