# Generated by Django 3.2.25 on 2024-08-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0017_alter_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='sub_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_post', to='Community.sub_post'),
        ),
    ]
